### ISSUE TITLE
Aster Plot not Rendering in HTML

### ISSUE THREAD

**Issue by mikhailchester** [bbest/ohi-aster#1]
Ben: the files that I download from the repository aren't rendering in HTML. I've tried Chrome, Firefox, and Safari. It appears that draw.js isn't creating the SVG chart. Please let me know if the issue is on my end or if I'm missing something. Thanks.

**Comment by bbest** [comment]
Hi @mikhailchester,

Ah yes, that's because the loading of JavaScript libraries requires you to run from a webserver. If not, then inspecting the locally loaded index.html, which turns up blank, in Google Chrome's [Javascript Console](https://developer.chrome.com/devtools/docs/console) reveals some files not being found.

![image](https://cloud.githubusercontent.com/assets/2837257/8017058/647f13fc-0ba1-11e5-9765-d1fdfc92e374.png)

The easiest way I know to get a web server running is using the [Python](https://www.python.org) programming language, which is already included with any modern Mac OS and an easy install on Windows. So you would in Terminal (Mac) or DOS command window (Win), run the following:

``` bash
# change directory to this repo's folder
cd ~/github/ohi-aster

# run Python web server
python -m SimpleHTTPServer
```

Then you can visit [http://localhost:8000](http://localhost:8000) to see a functional index.html.

![image](https://cloud.githubusercontent.com/assets/2837257/8017080/ee28f9ba-0ba1-11e5-92e4-caec62563773.png)

PS Would love to hear how you're using this visualization.
